### ISSUE TITLE
A list of issues existing right now (19.09.21)

### ISSUE THREAD

**Issue by Fr0dech** [LambdaGaming/ricochet-source-2#1] opened 2021-09-19 20:56 UTC
- Freeze power-up actually not freezing
- Disc going through power-up (even if there's no power-up) doing collision sound and particle effect (at least, don't ricochet)
- After several collisions (including collision with player in certain circumstances) disc changes its angle and doesn't fly how intended
- Hitting a player pushes him in wrong direction (looks like its random lol)

_This is issues that are not in to-do list_

**Comment by LambdaGaming** [comment] 2021-09-23 02:26
The first two issues should be fixed. The other two are partially fixed.

I don't know the exact cause of the third issue but I'm assuming it has something to do with the physics engine. If possible, I'm gonna try to make the disc entity have it's own physics so it only moves and changes direction when I want it to.

As for the fourth issue, I think the problem is that the disc is changing direction before the `StartTouch` function is called, so the player is moving in the direction of the disc after it ricochets. I don't know if this can be fixed at the moment since it seems like that's the way the entity class is designed internally, but maybe fixing the third issue will fix this one as well.

I'm gonna close this issue and create more detailed reports of the last two issues in the To-Do. If you find anything else feel free to create another issue.

**Closed by LambdaGaming** 2021-09-23 02:26 UTC
Labels: bug
